### ISSUE TITLE
Create a MD template for the creation of issues

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#2] opened 2024-10-31 17:41 UTC
## Summary
- Create a markdown file that holds a template with required and important details to fill in when proposing an issue
- Feel free to propose a template
- This template should be just a guide don't add to much text with the headers is ok

**Comment by ShantelPeters** [comment] 2024-10-31 18:09
Hi @danielcdz please can I be assigned to this issue?

**Comment by Oshioke-Salaki** [comment] 2024-10-31 18:11
I’d love to work on this task.

**Comment by 0xdevcollins** [comment] 2024-10-31 18:14
Can I try solving this issue?

**Comment by Gerson2102** [comment] 2024-10-31 18:17
Hey mate, I can help you with this. Lmk!

**Comment by JosueBrenes** [comment] 2024-10-31 18:18
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

# Proposed Solution for Issue

I would resolve this issue in the following way:

1. **Create a Markdown Template**: Start by creating a Markdown file named `ISSUE_TEMPLATE.md` to define a template that includes essential fields for issue proposals.

2. **Define Key Headers**: Ensure the template includes headers for important details that need to be filled out, such as:
   - **Title**: A clear, concise title for the issue.
   - **Description**: A brief summary of the issue and any relevant context.
   - **Steps to Reproduce**: A list of steps to replicate the issue if it’s a bug.
   - **Expected Behavior**: What the expected outcome is.
   - **Actual Behavior**: What currently happens, including any error messages.
   - **Environment**: Information about the environment where the issue occurs (e.g., OS, browser version).
   - **Additional Context**: Any other relevant details or screenshots.

3. **Keep it Minimal**: Since the requester asked for the template to be minimal, avoid adding any excessive instructions or filler text. Each section header should serve as a prompt, making it easy for users to fill in only the necessary information.

4. **Testing and Reviewing**: After creating the file, test it by submitting a sample issue to ensure the format is user-friendly and achieves the intended goal.

**Comment by Gerson2102** [comment] 2024-10-31 18:21
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by Benjtalkshow** [comment] 2024-10-31 18:28
Can I tackle this one?

**Comment by diegoTech14** [comment] 2024-10-31 18:31
Hello, I'm Diego a software engineer from Costa Rica and member of Dojo Coding ⛩️ I've created some documentation for projects like KaizenNodeLabs, ByteBeasts and Dipdup, I would love to contribute to this issue



#### I have some experience documenting projects and I have an idea of how the template will looks already:

1. Issue Title
2. Description of the issue
3. Steps to solve the issue
4. Acceptance criteria

Kind regards,

Diego Duarte Fernández

**Comment by gadyrcdz** [comment] 2024-10-31 18:33
May I try my hand at this? I'm part of the Dojo Coding Community

**Comment by lauchaves** [comment] 2024-10-31 18:37
Hey Im Lau Chaves Id would like to contribute to this one! Im a member of Dojo Coding Costa RicaI have already helped other mainteners creating issues and would love to do the md file for this project! 

Please check some issues template on these links: 

https://github.com/keep-starknet-strange/joyboy/issues/249
https://github.com/keep-starknet-strange/joyboy/issues/232
.... 

Most of them got a description, issue, expected and screenshot sections

<img width="724" alt="image" src="https://github.com/user-attachments/assets/8d9289ae-5a49-42ff-8c69-2adc74ac1465">

**Comment by 0xBinayak** [comment] 2024-10-31 18:40
# Issue Title

## Description


## Steps to Reproduce
1. Step 1
2. Step 2
3. Step 3

## Expected Behavior


## Actual Behavior


## Environment
- **OS**: 
- **Browser/Version**: 
- **Other Relevant Software Versions**: 

## Possible Solution (Optional)


## Additional Context/Screenshots

 

Example Template

**Comment by omsant02** [comment] 2024-10-31 18:46
I’d love to work on this task.

**Closed as completed** 2024-11-01 18:15 UTC
Labels: documentation, good first issue, ODHACK9
